#!/bin/sh
options="Poweroff\nReboot\nUpdate system\nConnect ssid(iwctl)(iwd)\nConnect to ethernet\nTask manager\nSystem info\nNothing"
choice=$(echo -e $options | rofi -config ~/.config/rofi/config-system-menu.rasi -dmenu)
case $choice in
    "Poweroff")
        systemctl poweroff
        ;;
    "Reboot")
        systemctl reboot
        ;;
    "Update system")
        exec kitty --app-id upd ~/lsa/SH/update-sys 
        ;;
    "Connect ssid(iwctl)(iwd)")
        exec kitty --app-id sys-info ~/lsa/SH/connect-iwctl
        ;;
    "Connect to ethernet")
        exit
        ;;
    "System info")
        exec kitty --app-id sys-info ~/lsa/SH/sys-info
        ;;
    "Task manager")
        exec kitty --app-id btop btop
        ;;
    *)
        exit 
        ;;
esac
